@startuml
abstract class AbstractTodolistCopy {
    {abstract} T copy()
    {abstract} bool map_todolist()
    {abstract} void copy_default_extend()
}
note left: In this Case T is CrmLead

Class CrmLead {
    + CrmStage stage_id
    + void copy_default_extend()
    + Dobtor_TodoList_core[] todolist_ids
}

Class Dobtor_TodoList_core {
    + T ref_id
}
note left: In this Case T is CrmLead

Class CrmStage {
    + CrmStage get_stage_new()
}


AbstractTodolistCopy <|-- CrmLead
CrmLead "*" -o "1" CrmStage
CrmLead "1" o-- "*" Dobtor_TodoList_core
@enduml