#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""End-to-end verification for the ``dobtor_apikey_scope`` module.

It proves, over real XML-RPC (the primary API-key transport, which runs under
``borrow_request`` -- exactly the path this module had to solve), that a
*restricted* API key loses access to a model its owner could otherwise reach,
while an *unrestricted* key keeps it. If the scope narrowing did not actually
take effect at the ORM layer, step 2 below would wrongly succeed and the script
prints FAIL.

--------------------------------------------------------------------------
Why keys are created in the UI, not here
--------------------------------------------------------------------------
API keys are generated by the ``res.users.apikeys.description`` wizard, which
requires an interactive identity check and calls the private ``_generate``
(RPC forbids ``_``-prefixed methods). So key creation stays in the product UI
-- which is exactly the feature we want to exercise -- and this script consumes
the two resulting keys.

--------------------------------------------------------------------------
Usage
--------------------------------------------------------------------------
1) Create the fixtures (test group + ACL + test user) as an administrator:

     python3 verify_apikey_scope.py setup \
         --url http://localhost:8069 --db YOURDB \
         --admin-login admin --admin-password ADMIN_PW \
         --test-password test1234

   This creates:
     * group  "API Scope Test"
     * ACL    read access to ``ir.config_parameter`` for that group
     * user   login "apikey_scope_tester" with groups [Internal User, API Scope Test]

2) Log in to Odoo as ``apikey_scope_tester`` (password from --test-password),
   open  My Profile > Account Security  and generate TWO API keys:
     * KEY_FULL       : "Limit permissions" = OFF  (or ON with all groups ticked)
     * KEY_RESTRICTED : "Limit permissions" = ON, tick ONLY "Internal User"
                        (leave "API Scope Test" unticked)

3) Run the checks:

     python3 verify_apikey_scope.py verify \
         --url http://localhost:8069 --db YOURDB \
         --login apikey_scope_tester \
         --key-full KEY_FULL --key-restricted KEY_RESTRICTED

Exit code is non-zero if any check fails.
"""
import argparse
import sys
import xmlrpc.client

TEST_GROUP_NAME = "API Scope Test"
TEST_LOGIN = "apikey_scope_tester"
# base.group_user can read res.partner but NOT ir.config_parameter; the test
# group grants read on ir.config_parameter, so scope narrowing is observable.
ALLOWED_MODEL = "res.partner"          # readable via the floor group (Internal User)
DENIED_MODEL = "ir.config_parameter"   # readable only via the test group


def _endpoints(url):
    common = xmlrpc.client.ServerProxy(f"{url}/xmlrpc/2/common")
    models = xmlrpc.client.ServerProxy(f"{url}/xmlrpc/2/object")
    return common, models


def _ref(models, db, uid, pw, module, name):
    """Resolve an XML id to its database id via ir.model.data."""
    rows = models.execute_kw(
        db, uid, pw, 'ir.model.data', 'search_read',
        [[('module', '=', module), ('name', '=', name)]],
        {'fields': ['res_id'], 'limit': 1})
    if not rows:
        raise SystemExit(f"Could not resolve {module}.{name}")
    return rows[0]['res_id']


def cmd_setup(args):
    common, models = _endpoints(args.url)
    uid = common.authenticate(args.db, args.admin_login, args.admin_password, {})
    if not uid:
        raise SystemExit("Admin authentication failed.")
    pw = args.admin_password

    group_user_id = _ref(models, args.db, uid, pw, 'base', 'group_user')

    # 1. test group (idempotent)
    grp = models.execute_kw(args.db, uid, pw, 'res.groups', 'search_read',
                            [[('name', '=', TEST_GROUP_NAME)]], {'fields': ['id'], 'limit': 1})
    if grp:
        group_id = grp[0]['id']
        print(f"= group '{TEST_GROUP_NAME}' already exists (id={group_id})")
    else:
        group_id = models.execute_kw(args.db, uid, pw, 'res.groups', 'create',
                                     [{'name': TEST_GROUP_NAME}])
        print(f"+ created group '{TEST_GROUP_NAME}' (id={group_id})")

    # 2. ACL: read ir.config_parameter for the test group
    model_row = models.execute_kw(args.db, uid, pw, 'ir.model', 'search_read',
                                  [[('model', '=', DENIED_MODEL)]], {'fields': ['id'], 'limit': 1})
    model_id = model_row[0]['id']
    acl_name = f"{DENIED_MODEL}.scope_test.read"
    acl = models.execute_kw(args.db, uid, pw, 'ir.model.access', 'search_read',
                            [[('name', '=', acl_name)]], {'fields': ['id'], 'limit': 1})
    if acl:
        print(f"= ACL '{acl_name}' already exists")
    else:
        models.execute_kw(args.db, uid, pw, 'ir.model.access', 'create', [{
            'name': acl_name,
            'model_id': model_id,
            'group_id': group_id,
            'perm_read': True,
            'perm_write': False,
            'perm_create': False,
            'perm_unlink': False,
        }])
        print(f"+ created ACL '{acl_name}' (read {DENIED_MODEL} for test group)")

    # 3. test user
    usr = models.execute_kw(args.db, uid, pw, 'res.users', 'search_read',
                            [[('login', '=', TEST_LOGIN)]], {'fields': ['id'], 'limit': 1})
    if usr:
        user_id = usr[0]['id']
        models.execute_kw(args.db, uid, pw, 'res.users', 'write',
                          [[user_id], {'groups_id': [(4, group_id)], 'password': args.test_password}])
        print(f"= user '{TEST_LOGIN}' already exists (id={user_id}); ensured group + password")
    else:
        user_id = models.execute_kw(args.db, uid, pw, 'res.users', 'create', [{
            'name': "API Scope Tester",
            'login': TEST_LOGIN,
            'password': args.test_password,
            'groups_id': [(6, 0, [group_user_id, group_id])],
        }])
        print(f"+ created user '{TEST_LOGIN}' (id={user_id})")

    print("\nNext: log in as", TEST_LOGIN, "and create two API keys (see this file's header),")
    print("then run the 'verify' sub-command.")


def _read_one(models, db, uid, key, model):
    """Attempt a search_read of one record; return (ok, detail)."""
    try:
        models.execute_kw(db, uid, key, model, 'search_read',
                          [[]], {'fields': ['id'], 'limit': 1})
        return True, "read OK"
    except xmlrpc.client.Fault as f:
        first = f.faultString.strip().splitlines()[0] if f.faultString else str(f)
        return False, first


def cmd_verify(args):
    common, models = _endpoints(args.url)

    uid_r = common.authenticate(args.db, args.login, args.key_restricted, {})
    uid_f = common.authenticate(args.db, args.login, args.key_full, {})
    if not uid_r or not uid_f:
        raise SystemExit("API-key authentication failed (bad key/login/db).")
    if uid_r != uid_f:
        raise SystemExit("The two keys resolve to different users.")

    results = []

    ok, detail = _read_one(models, args.db, uid_r, args.key_restricted, ALLOWED_MODEL)
    results.append((f"restricted key CAN read {ALLOWED_MODEL}", ok, detail))

    ok, detail = _read_one(models, args.db, uid_r, args.key_restricted, DENIED_MODEL)
    # PASS means it was correctly DENIED
    results.append((f"restricted key CANNOT read {DENIED_MODEL}", (not ok), detail))

    ok, detail = _read_one(models, args.db, uid_f, args.key_full, DENIED_MODEL)
    results.append((f"full key CAN read {DENIED_MODEL} (control)", ok, detail))

    print(f"\nUser id: {uid_r}\n")
    width = max(len(name) for name, _, _ in results)
    all_pass = True
    for name, passed, detail in results:
        all_pass &= passed
        print(f"  [{'PASS' if passed else 'FAIL'}] {name.ljust(width)}   ({detail})")

    print()
    if all_pass:
        print("RESULT: PASS -- API key permission scope is enforced over XML-RPC.")
        return 0
    print("RESULT: FAIL -- narrowing did not behave as expected (see rows above).")
    return 1


def main():
    p = argparse.ArgumentParser(description="Verify dobtor_apikey_scope end-to-end.")
    sub = p.add_subparsers(dest="cmd", required=True)

    s = sub.add_parser("setup", help="create test group/ACL/user as admin")
    s.add_argument("--url", required=True)
    s.add_argument("--db", required=True)
    s.add_argument("--admin-login", required=True)
    s.add_argument("--admin-password", required=True)
    s.add_argument("--test-password", default="test1234")
    s.set_defaults(func=cmd_setup)

    v = sub.add_parser("verify", help="run enforcement checks with two API keys")
    v.add_argument("--url", required=True)
    v.add_argument("--db", required=True)
    v.add_argument("--login", default=TEST_LOGIN)
    v.add_argument("--key-full", required=True)
    v.add_argument("--key-restricted", required=True)
    v.set_defaults(func=cmd_verify)

    args = p.parse_args()
    rc = args.func(args)
    sys.exit(rc or 0)


if __name__ == "__main__":
    main()
